/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Index: typeof import('./src/components/pages/home-view/Index.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoginForm: typeof import('./src/components/pages/auth/login/LoginForm.vue')['default']
    Password: typeof import('primevue/password')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TInputText: typeof import('./src/components/ui/TInputText.vue')['default']
  }
}
